name: cdci

on: push

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.5.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: bundle the reverse_string_handler
        run: |
          zip -j reverse_string_lambda.zip index.js

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform validate
        run: terraform validate -json

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color

        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -no-color

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.5.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: copy file to bucket
        run: |
          aws s3 cp example.txt s3://plain-string-bucket/

      - name: test the reverse-string-handler
        run: |
          source <(curl -sSf https://raw.githubusercontent.com/chiefbiiko/bashert/v1.0.1/bashert.sh)
          source ./test_suite.sh
          test_reverse_string_204
          test_string_has_been_reversed
          test_reverse_string_400
          test_reverse_string_500
