name: cx

on: push

env:
  AWS_REGION: us-east-1

defaults:
  run:
    shell: "/bin/bash {0}"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.5.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run: terraform init

      - name: Terraform validate
        run: terraform validate -no-color

      - name: map branch 2 test/prod
        run: |
          if [[ ${{ github.ref }} == *main ]]; then
            echo "ENVIRONMENT=test" >> $GITHUB_ENV # TODO: revert 2 prod
          else
            echo "ENVIRONMENT=test" >> $GITHUB_ENV
          fi

      - name: configure the environment
        id: configure_environment
        run: |
          echo "REVERSE_STRING=reverse-string" >> $GITHUB_ENV
          echo "STRING=string" >> $GITHUB_ENV

      - name: Terraform Plan
        id: plan
        # if: github.event_name == 'pull_request'
        run: |
          terraform plan \
            -no-color \
            -var="reverse_string=$ENVIRONMENT-$REVERSE_STRING" \
            -var="string=$ENVIRONMENT-$STRING" 

        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          terraform apply \
            -auto-approve \
            -no-color \
            -var="reverse_string=$ENVIRONMENT-$REVERSE_STRING" \
            -var="string=$ENVIRONMENT-$STRING"
