name: cx

on: push

env:
  AWS_REGION: us-east-1

defaults:
  run:
    shell: "/bin/bash {0}"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.5.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1.2.1        

      - name: Terraform fmt
        id: format
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform validate
        run: terraform validate -no-color
